/* pipe.c — anonymous pipes backed by a shared ring buffer.
 *
 * Each pipe is a kmalloc'd struct pipe containing a 4KB ring buffer and two
 * chardev VFS nodes (read end, write end) that share a pointer to it.
 *
 * read_op  blocks (hlt loop) when the buffer is empty and the write end is
 *          still open; returns 0 (EOF) when the write end is closed and the
 *          buffer is drained.
 * write_op blocks when the buffer is full and the read end is still open;
 *          returns (uint32_t)-1 (broken pipe) when the read end is closed.
 *
 * Up to PIPE_MAX concurrent pipes are supported via a static slot table.
 * Each slot gets its own read_op/write_op function (generated by macro) that
 * closes over the slot index and recovers the struct pipe from the table.
 */

#include <stdint.h>
#include <string.h>

#include "kernel/pipe.h"
#include "kernel/heap.h"
#include "kernel/kernel.h"
#include "kernel/sched.h"
#include "kernel/task.h"
#include "kernel/vfs.h"
#include "cpu/x86.h"

/* ── ring buffer helpers ───────────────────────���─────────────────────────── */

#define PIPE_MASK (PIPE_BUF_SIZE - 1)

static inline uint32_t pipe_used(const struct pipe *p)
{
    return (p->head - p->tail) & PIPE_MASK;
}

static inline uint32_t pipe_free(const struct pipe *p)
{
    return PIPE_BUF_SIZE - 1 - pipe_used(p);
}

/* ── slot table ────────────────────────────────────────────────────────��─── */

#define PIPE_MAX 16

struct pipe_entry {
    struct pipe     *p;
    struct vfs_node *read_node;
    struct vfs_node *write_node;
};

static struct pipe_entry pipe_table[PIPE_MAX];

/* ── per-slot op functions ───────────────────────────────────────────��───── */
/* Each slot gets its own read_op and write_op via macro expansion.
 * This avoids needing a context pointer in the VFS op signature. */

#define PIPE_SLOT(i)                                                            \
static uint32_t pipe_read_##i(uint32_t off, uint32_t len, void *buf)           \
{                                                                               \
    (void)off;                                                                  \
    struct pipe *p = pipe_table[i].p;                                           \
    char *cbuf = (char *)buf;                                                   \
    uint32_t out = 0;                                                           \
    while (out < len) {                                                         \
        if (pipe_used(p) == 0) {                                                \
            if (p->write_refs == 0) break; /* EOF: no writers remain */         \
            if (out > 0) break; /* return what we already have */               \
            if (running_task && running_task->read_nonblock) break; /* non-blocking */ \
            enable_interrupts();                                                \
            asm volatile("hlt");                                                \
            disable_interrupts();                                               \
            continue;                                                           \
        }                                                                       \
        cbuf[out++] = p->buf[p->tail & PIPE_MASK];                             \
        p->tail++;                                                              \
    }                                                                           \
    return out;                                                                 \
}                                                                               \
static uint32_t pipe_write_##i(uint32_t off, uint32_t len, const void *buf)    \
{                                                                               \
    (void)off;                                                                  \
    struct pipe *p = pipe_table[i].p;                                           \
    const char *cbuf = (const char *)buf;                                       \
    if (p->read_refs == 0) return (uint32_t)-1; /* broken pipe */              \
    uint32_t written = 0;                                                       \
    while (written < len) {                                                     \
        if (pipe_free(p) == 0) {                                                \
            if (p->read_refs == 0) return (uint32_t)-1;                        \
            enable_interrupts();                                                \
            asm volatile("hlt");                                                \
            disable_interrupts();                                               \
            continue;                                                           \
        }                                                                       \
        p->buf[p->head & PIPE_MASK] = cbuf[written++];                         \
        p->head++;                                                              \
    }                                                                           \
    return written;                                                             \
}

PIPE_SLOT(0)  PIPE_SLOT(1)  PIPE_SLOT(2)  PIPE_SLOT(3)
PIPE_SLOT(4)  PIPE_SLOT(5)  PIPE_SLOT(6)  PIPE_SLOT(7)
PIPE_SLOT(8)  PIPE_SLOT(9)  PIPE_SLOT(10) PIPE_SLOT(11)
PIPE_SLOT(12) PIPE_SLOT(13) PIPE_SLOT(14) PIPE_SLOT(15)

typedef uint32_t (*pipe_op_read_t)(uint32_t, uint32_t, void *);
typedef uint32_t (*pipe_op_write_t)(uint32_t, uint32_t, const void *);

static const pipe_op_read_t slot_read[PIPE_MAX] = {
    pipe_read_0,  pipe_read_1,  pipe_read_2,  pipe_read_3,
    pipe_read_4,  pipe_read_5,  pipe_read_6,  pipe_read_7,
    pipe_read_8,  pipe_read_9,  pipe_read_10, pipe_read_11,
    pipe_read_12, pipe_read_13, pipe_read_14, pipe_read_15,
};

static const pipe_op_write_t slot_write[PIPE_MAX] = {
    pipe_write_0,  pipe_write_1,  pipe_write_2,  pipe_write_3,
    pipe_write_4,  pipe_write_5,  pipe_write_6,  pipe_write_7,
    pipe_write_8,  pipe_write_9,  pipe_write_10, pipe_write_11,
    pipe_write_12, pipe_write_13, pipe_write_14, pipe_write_15,
};

/* ── pipe_notify_close ───────────────────────��───────────────────────────── */
/* Called by sys_close when closing a pipe node.
 * Updates write_closed / read_closed flags; frees the struct pipe when both
 * ends are closed (the VFS nodes themselves remain in the pool — they are
 * cheap static structs). */

void pipe_notify_close(struct vfs_node *node)
{
    for (int i = 0; i < PIPE_MAX; i++) {
        if (!pipe_table[i].p) continue;
        if (node == pipe_table[i].read_node) {
            if (pipe_table[i].p->read_refs > 0)
                pipe_table[i].p->read_refs--;
            if (pipe_table[i].p->read_refs == 0 &&
                pipe_table[i].p->write_refs == 0) {
                kfree(pipe_table[i].p);
                pipe_table[i].p = NULL;
                vfs_free_node(pipe_table[i].read_node);
                vfs_free_node(pipe_table[i].write_node);
                pipe_table[i].read_node  = NULL;
                pipe_table[i].write_node = NULL;
            }
            return;
        }
        if (node == pipe_table[i].write_node) {
            if (pipe_table[i].p->write_refs > 0)
                pipe_table[i].p->write_refs--;
            if (pipe_table[i].p->read_refs == 0 &&
                pipe_table[i].p->write_refs == 0) {
                kfree(pipe_table[i].p);
                pipe_table[i].p = NULL;
                vfs_free_node(pipe_table[i].read_node);
                vfs_free_node(pipe_table[i].write_node);
                pipe_table[i].read_node  = NULL;
                pipe_table[i].write_node = NULL;
            }
            return;
        }
    }
}

void pipe_fork_fd(struct vfs_node *node)
{
    for (int i = 0; i < PIPE_MAX; i++) {
        if (!pipe_table[i].p) continue;
        if (node == pipe_table[i].read_node) {
            pipe_table[i].p->read_refs++;
            return;
        }
        if (node == pipe_table[i].write_node) {
            pipe_table[i].p->write_refs++;
            return;
        }
    }
}

/* ── pipe_create ─────────────────────────────────────────��───────────────── */

int pipe_create(struct vfs_node **read_out, struct vfs_node **write_out)
{
    /* Find a free slot */
    int slot = -1;
    for (int i = 0; i < PIPE_MAX; i++) {
        if (!pipe_table[i].p) { slot = i; break; }
    }
    if (slot < 0) return -1;

    struct pipe *p = (struct pipe *)kmalloc(sizeof(struct pipe));
    if (!p) return -1;
    memset(p, 0, sizeof(*p));
    p->write_refs = 1;
    p->read_refs  = 1;

    struct vfs_node *rnode = vfs_alloc_node();
    struct vfs_node *wnode = vfs_alloc_node();
    if (!rnode || !wnode) {
        kfree(p);
        return -1;
    }

    rnode->flags    = VFS_FILE | VFS_CHARDEV;
    rnode->inode    = 200 + (uint32_t)slot * 2;
    rnode->read_op  = slot_read[slot];
    rnode->write_op = NULL;

    wnode->flags    = VFS_FILE | VFS_CHARDEV;
    wnode->inode    = 201 + (uint32_t)slot * 2;
    wnode->read_op  = NULL;
    wnode->write_op = slot_write[slot];

    pipe_table[slot].p          = p;
    pipe_table[slot].read_node  = rnode;
    pipe_table[slot].write_node = wnode;

    *read_out  = rnode;
    *write_out = wnode;
    return 0;
}
