#!/usr/bin/env python3

"""
Dynamically generates vectors.s which contains the entry points for all
CPU traps and interrupts.

Usage:
    python3 mkvectors.py > vectors.s
"""

import datetime

all_vectors = range(0, 256)
with_error_code = set([8, 10, 11, 12, 13, 14, 17])
irq_vectors = range(32, 48)

print('# generated by mkvectors.py at %s - do not edit' % datetime.datetime.now().isoformat())
print()
print('.section .text')
print()

print('# handlers')
for i in all_vectors:
    print('.globl vector%d' % i)
    print('vector%d:' % i)
    if i in irq_vectors:
        print('    # IRQ%d' % (i-32))
        print('    pushl $0')
        print('    pushl $%d' % i)
    else:
        if i in with_error_code:
            print('    pushl $0')
        print('    pushl $%d' % i)
    print('    jmp alltraps')
print()

print('.section .data')
print()
print('# vector table')
print('.globl vectors')
print('vectors:')
for i in all_vectors:
    print('    .long vector%d' % i)
print()
print('# end of file')
