#!/bin/sh
# gen_symtab.sh <nm> <addr2line> <kernel-elf> <output-c>
# Generates kernel/symtab_gen.c with function names and file:line info.
# addr2line is invoked once for all addresses.

NM="$1"
ADDR2LINE="$2"
ELF="$3"
OUT="$4"

EMPTY_TABLE='/* AUTO-GENERATED by tools/gen_symtab.sh */
#include <stdint.h>
#include "kernel/symtab.h"
const struct ksym ksym_table[] = { { 0, "(no symbols)" } };
const uint32_t ksym_count = 1;'

if [ -z "$NM" ] || [ -z "$ADDR2LINE" ] || [ -z "$ELF" ] || [ -z "$OUT" ]; then
    echo "Usage: $0 <nm> <addr2line> <kernel.elf> <output.c>" >&2
    exit 1
fi

if [ ! -f "$ELF" ]; then
    echo "gen_symtab: $ELF not found, writing empty table" >&2
    printf '%s\n' "$EMPTY_TABLE" > "$OUT"
    exit 0
fi

# Extract text symbols: "addr name" pairs, sorted by address
SYMS=$("$NM" --numeric-sort "$ELF" 2>/dev/null | grep ' [Tt] ' | awk '{print $1, $3}')

if [ -z "$SYMS" ]; then
    echo "gen_symtab: no text symbols found in $ELF" >&2
    printf '%s\n' "$EMPTY_TABLE" > "$OUT"
    exit 0
fi

TMP_SYMS=$(mktemp)
TMP_A2L=$(mktemp)
TMP_ROWS=$(mktemp)

# Single addr2line invocation for all addresses.
# -f outputs two lines per address: function name then file:line.
# Collapse each pair into one tab-separated line with paste.
echo "$SYMS" | awk '{printf "0x%s\n", $1}' | xargs "$ADDR2LINE" -e "$ELF" -f 2>/dev/null \
    | paste - - > "$TMP_A2L"
echo "$SYMS" > "$TMP_SYMS"

# Merge syms (addr name) with a2l (funcname\tfile:line), one line each.
paste "$TMP_SYMS" "$TMP_A2L" | awk -F'\t' '
{
    split($1, sym, " ")
    addr     = sym[1]
    name     = sym[2]
    fileline = $3

    sub(".*/", "", fileline)   # strip directory path

    if (fileline ~ /^\?\?/ || fileline ~ /:\?$/ || fileline ~ /:0$/ || fileline == "") {
        label = name
    } else {
        label = name " (" fileline ")"
    }

    gsub(/\\/, "\\\\", label)
    gsub(/"/, "\\\"", label)
    printf "    { 0x%s, \"%s\" },\n", addr, label
}' > "$TMP_ROWS"

COUNT=$(echo "$SYMS" | wc -l | tr -d ' ')

{
    echo "/* AUTO-GENERATED by tools/gen_symtab.sh — do not edit by hand. */"
    echo "#include <stdint.h>"
    echo "#include \"kernel/symtab.h\""
    echo ""
    echo "const struct ksym ksym_table[] = {"
    cat "$TMP_ROWS"
    echo "};"
    echo "const uint32_t ksym_count = ${COUNT}u;"
} > "$OUT"

rm -f "$TMP_SYMS" "$TMP_A2L" "$TMP_ROWS"
echo "gen_symtab: wrote $COUNT symbols to $OUT"
