#!/bin/sh

echo "// generated by $(realpath $0) at $(date -Iseconds) - do not edit"
v=$(git describe --abbrev=7 --dirty --always --tags)
echo "#define KERNEL_VERSION \"$v\""
h=$(git rev-parse HEAD)
echo "#define _GIT_LAST_COMMIT \"$h\""
